### ISSUE TITLE
nightly rebuilds of ius-release breaks reposync/yum

### ISSUE THREAD

**Issue by divad** [iuscommunity-pkg/ius-release#5]
Hello,

It would seem that IUS has started to rebuild the "ius-release" RPM every day. The RPM itself is not changing, the version/release stays the same, but the resulting RPM file differs because the build date has changed, thus the RPM file is different at a binary level every day. 

reposync notices every day when we run it that the ius-release file has changed. It goes to download it - but this breaks reposync/yum because yum seems to incorrectly assume that it is resuming a download if the file size is larger than the day before, thus sending a HTTP range request, and this results in a HTTP 416 range not satisfiable. 

A workaround is to delete the repository mirror every day and then re-download it, but obviously this is not a good solution. Another odd workaround is to set "async=0" in the yum repo file for 'ius' which causes yum to delete the old file when it breaks and then on the subsequent reposync run, it works because there is no existing file to 'resume'. 

It looks like the reposync/yum behaviour is a bug: https://bugzilla.redhat.com/show_bug.cgi?id=1337957 but given the bug is in yum its unlikely to be fixed any time soon. I can't think of any good reason for rebuilding the same RPM every single day without updating the release number, so I'd like to suggest that IUS should stop rebuilding ius-release every single day.

Thanks in advance!

**Comment by divad** [comment]
Here is a bug report for RHEL7 with the exact same issue: https://bugzilla.redhat.com/show_bug.cgi?id=1399235

**Comment by b-harper** [comment]
Hey @divad,

Thanks for taking the time to submit this issue and chat on IRC.  We know that reposync is used by many people, but this is the first time we have heard of this issue.  Can you update this issue with your configuration? 

-Ben

**Comment by divad** [comment]
The machine running reposync is RHEL 7.3 server 64-bit.

We install 'ius-release' and then run reposync like this:

``reposync --repoid=ius -p /mirror --download-metadata -m``

**Comment by divad** [comment]
I was incorrect; the RPM is not being rebuilt everyday, it is being re-signed every day.

The first RPM I downloaded:
``Signature   : DSA/SHA1, Sun 05 Mar 2017 05:17:39 GMT, Key ID da221cdf9cd4953f``

And today's:
``Signature   : DSA/SHA1, Tue 07 Mar 2017 05:19:11 UTC, Key ID da221cdf9cd4953f``

**Comment by b-harper** [comment]
After some additional conversation on IRC,  it was recommended to exclude ius-release.  In general, it is a good idea when running your own repositories, but it will also work around this issue.  This issue will get fixed when current automation gets replaced.
